name: Stargazers Badge and Report

on:
  schedule:
    - cron: '0 * * * *' # run hourly
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write

jobs:
  fetch-stargazers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch stargazers total
        run: |
          REPOS=(
            "agjgd/agjgd"
            "agjjQuery/agjjQuery"
            "andrewgjohnson/agjCalendar"
            "andrewgjohnson/andrewgjohnson"
            "andrewgjohnson/ctcCache"
            "andrewgjohnson/ctcSerializer"
            "andrewgjohnson/eslint-config-google-jsdocless"
            "andrewgjohnson/imageblendedcolorallocate"
            "andrewgjohnson/imagecolorallocatefromstring"
            "andrewgjohnson/imagegradientrectangle"
            "andrewgjohnson/imagettftextblur"
            "andrewgjohnson/imagettftextgradient"
            "andrewgjohnson/linebreaks4imagettftext"
          )
          UNIQUE_IDS=()
          REPO_STARGAZERS=()

          for REPO in "${REPOS[@]}"; do
            PAGE=1
            STARGAZERS=0
            while true; do
              RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO/stargazers?per_page=100&page=$PAGE")
              if echo $RESPONSE | jq -e 'type == "array"' > /dev/null; then
                IDS=$(echo $RESPONSE | jq '.[].id')
                if [ -z "$IDS" ]; then
                  break
                fi
                for ID in $IDS; do
                  STARGAZERS=$((STARGAZERS + 1))
                  if [[ ! " ${UNIQUE_IDS[@]} " =~ " ${ID} " ]]; then
                    UNIQUE_IDS+=("$ID")
                  fi
                done
                if [ $(echo $RESPONSE | jq '. | length') -lt 5 ]; then
                  break
                fi
                PAGE=$((PAGE + 1))
              else
                echo "Error or no stargazers found for $REPO"
                break
              fi
            done
            REPO_STARGAZERS+=("$REPO $STARGAZERS")
          done

          # Sort REPO_STARGAZERS array by the number of stargazers (second field), then by repo name (first field)
          IFS=$'\n' SORTED_REPO_STARGAZERS=($(sort -k2,2nr -k1,1 <<<"${REPO_STARGAZERS[*]}"))
          unset IFS

          REPORT="Project|Stargazers\n-------|----------\n"
          for ENTRY in "${SORTED_REPO_STARGAZERS[@]}"; do
            REPO=$(echo $ENTRY | awk '{print $1}')
            STARGAZERS=$(echo $ENTRY | awk '{print $2}')
            USERNAME=$(echo $REPO | cut -d'/' -f1)
            REPO_NAME=$(echo $REPO | cut -d'/' -f2)
            REPORT+="[$USERNAME/**$REPO_NAME**](https://github.com/$REPO)|[$STARGAZERS](https://github.com/$REPO/stargazers)\n"
          done

          UNIQUE_STARGAZERS=${#UNIQUE_IDS[@]}
          REPORT+="**Unique stargazers across all projects**|**$UNIQUE_STARGAZERS**"
          echo -e "$REPORT" > STARGAZERS.md

          BADGE_URL="https://raster.shields.io/badge/stargazers-${UNIQUE_STARGAZERS}-0969da.png?colorA=1f2823&colorB=0969da&style=flat-square&logoColor=white&logo=github"
          echo "Downloading badge from URL: $BADGE_URL"
          curl -L "$BADGE_URL" -o stargazers-badge.png

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add STARGAZERS.md
          git add stargazers-badge.png
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update stargazers badge and report"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
